### ISSUE TITLE
Document Caching

### ISSUE THREAD

**Issue by reklawnos** [FreeJournal/freejournal#13]
@pdaian 
- Document index
- Document files
- Database

**Comment by reklawnos** [comment]
- Set up SQLAlchemy as a dependency
- Create readme
- Create a requirements.txt file for pip
- Set up configs for various RDBMSs
- Finalize object classes for documents and collections
- Wiki page to describe architecture
- Implement index caching
  - Expiring index
    - Store age/accesses
    - Bitcoin votes
  - Stored as database tables
- Implement document caching
  - Expiring documents
    - Age
    - Amount of traffic
  - Cachepath - path on disk
- Thumbnails - research libraries
- Research performance
- Cache API
- Unit tests

**Comment by pdaian** [comment]
I also added some relevant commits in pull request #20

**Comment by pdaian** [comment]
Finished.  Actual work: 15 developer hours
