### ISSUE TITLE
Bitcoin timestamping

### ISSUE THREAD

**Issue by reklawnos** [FreeJournal/freejournal#17]
@folayo

**Comment by pdaian** [comment]
@zhangwenx check out this link for sample code: https://github.com/petertodd/python-bitcoinlib/blob/master/examples/timestamp-op-ret.py

Getting this running and working will be a good start.  Let me know as soon as you have questions on this issue because I'm sure there will be :+1:

**Comment by pdaian** [comment]
http://www.proofofexistence.com/developers
