### ISSUE TITLE
Setup Bitmessage and the Bitmessage Listener on VPS

### ISSUE THREAD

**Issue by akkowal2** [FreeJournal/freejournal#26]

**Comment by FreeJournalVPS** [comment]
Bitmessage is successfully installed and passes unit tests on the bitcoin cloud VPS.  Consequently, I also figured out why bitmessage unit tests are failing on travis and I believe I can fix it so that the tests will be able to run on travis.

**Comment by pdaian** [comment]
That's awesome, thanks!  Three thumbs up :+1: :+1: :+1:

**Comment by FreeJournalVPS** [comment]
Bitmessage is now successfully installed and passes unit tests on the CrownCloud VPS.

**Comment by FreeJournalVPS** [comment]
Bitmessage is now successfully installed and passes unit tests on the Dynamic Lunanode VPS.

**Comment by akkowal2** [comment]
Bitmessage is now successfully installed and passes unit tests on vpsbg.eu

**Comment by akkowal2** [comment]
The virtual private servers are updated.  They can all be running the bitmessage listener and can receive and cache collections sent to the main channel address (test.py creates a test collection).
