### ISSUE TITLE
BitMessage test fails silently

### ISSUE THREAD

**Issue by pdaian** [FreeJournal/freejournal#29]
After running install.py, I run the test script and see the following output:

```
phil@phildesk ~/h/F/bitmessage> python test.py
Connected successfully
{u'inboxMessages': []}
Sending Broadcast...
Sending Message...
```

The script executes instantly, implying that no PoW has been performed.  Also, rerunning the script shows nothing in my inbox, which is inconsistent with the output I expect.

The test should somehow check for a successful broadcast to the network.  @akkowal2

**Comment by pdaian** [comment]
Disregard that, looks like it works.  I am durr.

**Comment by akkowal2** [comment]
Yeah, honestly, that file shouldn't even be in the repository anymore.  It's just an example of the api usage.  I'll delete that in the future.
